// scripts/ingest-ncsc-logging.ts
// NCSC Logging and Protective Monitoring — introduction to logging for security purposes
// Source: https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring
// Version: 2024

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-logging',
    name: 'NCSC Logging and Protective Monitoring',
    name_nl: 'NCSC Logging and Protective Monitoring',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Guidance on implementing logging and protective monitoring to detect, investigate, and respond to cyber security events across IT systems',
    scope_sectors: ['government', 'energy', 'all'],
    structure_description: 'Controls covering what to log, how to collect and store logs, how to analyse them for security events, and protective monitoring principles',
    source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    {
      control_number: '1',
      title: 'Define logging requirements',
      title_nl: 'Define logging requirements',
      description: 'Define what events need to be logged based on your risk assessment and the sensitivity of your systems. Consider regulatory requirements, threat intelligence, and the need to support incident investigation.',
      description_nl: 'Define what events need to be logged based on your risk assessment and the sensitivity of your systems. Consider regulatory requirements, threat intelligence, and the need to support incident investigation.',
      category: 'Logging Strategy',
      subcategory: 'Requirements definition',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Document logging requirements based on risk assessment. Define minimum logging events for each system type. Include authentication events, access decisions, configuration changes, and error conditions.',
      verification_guidance: 'Review logging requirements documentation. Verify requirements are based on risk assessment.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '2',
      title: 'Log authentication events',
      title_nl: 'Log authentication events',
      description: 'Log all authentication events including successful logins, failed logins, account lockouts, password changes, MFA challenges, and session terminations. Authentication logs are the most valuable source for detecting account compromise.',
      description_nl: 'Log all authentication events including successful logins, failed logins, account lockouts, password changes, MFA challenges, and session terminations. Authentication logs are the most valuable source for detecting account compromise.',
      category: 'What to Log',
      subcategory: 'Authentication events',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Configure all authentication systems to log success and failure events. Include source IP, user agent, MFA method, and timestamp. Log account lockout and unlock events.',
      verification_guidance: 'Verify authentication logging on sampled systems. Check for completeness of logged fields.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '3',
      title: 'Log access to sensitive data and systems',
      title_nl: 'Log access to sensitive data and systems',
      description: 'Log access to sensitive data stores, privileged systems, and security-relevant configurations. Include who accessed what, when, from where, and what actions they performed.',
      description_nl: 'Log access to sensitive data stores, privileged systems, and security-relevant configurations. Include who accessed what, when, from where, and what actions they performed.',
      category: 'What to Log',
      subcategory: 'Data access',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Enable audit logging on databases, file shares, and sensitive applications. Log read and write access to classified or personal data. Include user identity and accessed resource.',
      verification_guidance: 'Verify data access logging is enabled on sensitive systems. Check log completeness.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '4',
      title: 'Log configuration and system changes',
      title_nl: 'Log configuration and system changes',
      description: 'Log changes to system configuration, security settings, user accounts, and access policies. Configuration changes may indicate an attacker establishing persistence or weakening defences.',
      description_nl: 'Log changes to system configuration, security settings, user accounts, and access policies. Configuration changes may indicate an attacker establishing persistence or weakening defences.',
      category: 'What to Log',
      subcategory: 'Change logging',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Log all changes to security-relevant configuration: firewall rules, user account changes, privilege escalation, policy modifications. Use change management systems that generate audit trails.',
      verification_guidance: 'Verify configuration change logging. Test that policy changes generate audit records.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '5',
      title: 'Centralise log collection',
      title_nl: 'Centralise log collection',
      description: 'Forward logs from all sources to a centralised log management platform (SIEM). Centralisation enables correlation across sources, improves detection, and prevents log tampering on individual systems.',
      description_nl: 'Forward logs from all sources to a centralised log management platform (SIEM). Centralisation enables correlation across sources, improves detection, and prevents log tampering on individual systems.',
      category: 'Log Collection',
      subcategory: 'Centralisation',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Deploy a SIEM or log management platform. Forward logs from all systems using syslog, API, or agent-based collection. Verify log delivery and detect gaps.',
      verification_guidance: 'Review log source inventory against system inventory. Verify log delivery to SIEM. Check for collection gaps.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '6',
      title: 'Protect log integrity',
      title_nl: 'Protect log integrity',
      description: 'Protect logs from tampering, deletion, and unauthorised access. Logs should be write-once where possible. Apply access controls to limit who can read, modify, or delete logs.',
      description_nl: 'Protect logs from tampering, deletion, and unauthorised access. Logs should be write-once where possible. Apply access controls to limit who can read, modify, or delete logs.',
      category: 'Log Collection',
      subcategory: 'Integrity protection',
      level: null,
      iso_mapping: 'A.12.4.2',
      implementation_guidance: 'Use write-once storage for security logs. Restrict access to log management systems. Implement log integrity checking (hashing, signing). Separate log storage from the systems being monitored.',
      verification_guidance: 'Verify log storage access controls. Test integrity mechanisms. Confirm logs cannot be modified by system administrators of the monitored systems.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '7',
      title: 'Synchronise time sources',
      title_nl: 'Synchronise time sources',
      description: 'Synchronise all system clocks to a reliable time source using NTP. Accurate timestamps are required for log correlation, incident investigation, and forensic analysis.',
      description_nl: 'Synchronise all system clocks to a reliable time source using NTP. Accurate timestamps are required for log correlation, incident investigation, and forensic analysis.',
      category: 'Log Collection',
      subcategory: 'Time synchronisation',
      level: null,
      iso_mapping: 'A.12.4.4',
      implementation_guidance: 'Configure all systems to synchronise with authoritative NTP servers. Use at least two NTP sources. Monitor for time drift. Use UTC in all log timestamps.',
      verification_guidance: 'Verify NTP configuration on all systems. Check for time drift. Confirm UTC timestamps in logs.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '8',
      title: 'Define log retention periods',
      title_nl: 'Define log retention periods',
      description: 'Define and implement log retention periods based on regulatory requirements, incident investigation needs, and storage capacity. Typical retention is 12 months for security logs, with longer retention for critical systems.',
      description_nl: 'Define and implement log retention periods based on regulatory requirements, incident investigation needs, and storage capacity. Typical retention is 12 months for security logs, with longer retention for critical systems.',
      category: 'Log Management',
      subcategory: 'Retention',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Define retention periods per log type. Implement automated retention policies. Archive logs beyond retention to long-term storage if needed. Delete logs when retention expires.',
      verification_guidance: 'Review retention policy documentation. Verify automated enforcement. Check oldest available logs against policy.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '9',
      title: 'Implement detection rules and alerting',
      title_nl: 'Implement detection rules and alerting',
      description: 'Define detection rules in the SIEM to identify known attack patterns, suspicious behaviours, and policy violations. Generate alerts for security-relevant events and route them to appropriate responders.',
      description_nl: 'Define detection rules in the SIEM to identify known attack patterns, suspicious behaviours, and policy violations. Generate alerts for security-relevant events and route them to appropriate responders.',
      category: 'Protective Monitoring',
      subcategory: 'Detection rules',
      level: null,
      iso_mapping: 'A.16.1.2',
      implementation_guidance: 'Define detection use cases based on threat intelligence and MITRE ATT&CK framework. Implement rules for brute force, privilege escalation, lateral movement, and data exfiltration. Tune alert thresholds to manage false positives.',
      verification_guidance: 'Review detection rule coverage against known attack techniques. Test rules with simulated attacks. Check alert routing and response times.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
    {
      control_number: '10',
      title: 'Conduct regular log reviews',
      title_nl: 'Conduct regular log reviews',
      description: 'Beyond automated alerting, conduct regular manual reviews of logs to identify patterns and anomalies that automated rules may miss. Include review of privileged access logs, failed authentication patterns, and unusual data access.',
      description_nl: 'Beyond automated alerting, conduct regular manual reviews of logs to identify patterns and anomalies that automated rules may miss. Include review of privileged access logs, failed authentication patterns, and unusual data access.',
      category: 'Protective Monitoring',
      subcategory: 'Manual review',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Schedule regular log reviews (daily for critical systems, weekly for others). Focus on privileged access, failed authentications, and data access patterns. Document and investigate anomalies.',
      verification_guidance: 'Verify log review schedule and completion. Check documentation of findings and follow-up actions.',
      source_url: 'https://www.ncsc.gov.uk/collection/logging-and-protective-monitoring',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-logging.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
