// scripts/ingest-ncsc-ce.ts
// NCSC Cyber Essentials — 5 technical controls with sub-requirements
// Source: https://www.ncsc.gov.uk/cyberessentials/overview
// Version: Willow (2024)

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-ce',
    name: 'NCSC Cyber Essentials',
    name_nl: 'NCSC Cyber Essentials',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: 'Willow',
    effective_date: '2024-04-01',
    scope: 'Technical cybersecurity controls for all UK organisations seeking Cyber Essentials certification',
    scope_sectors: ['government', 'healthcare', 'finance', 'education', 'all'],
    structure_description: '5 technical control themes, each with specific sub-requirements for Cyber Essentials and Cyber Essentials Plus certification',
    source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    // 1. Firewalls
    {
      control_number: '1',
      title: 'Firewalls',
      title_nl: 'Firewalls',
      description: 'Every device that connects to the internet must be protected by a properly configured firewall (or equivalent network device). Firewalls create a buffer zone between the internet and your internal network. They are configured to allow or deny network traffic based on a set of rules.',
      description_nl: 'Every device that connects to the internet must be protected by a properly configured firewall (or equivalent network device). Firewalls create a buffer zone between the internet and your internal network. They are configured to allow or deny network traffic based on a set of rules.',
      category: 'Firewalls',
      subcategory: null,
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Ensure all devices connecting to the internet have a firewall enabled and properly configured. Change default passwords on firewalls. Block unauthenticated inbound connections by default.',
      verification_guidance: 'Check firewall rules on boundary devices. Verify default admin passwords have been changed. Confirm inbound connections are blocked by default.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '1.1',
      title: 'Boundary firewalls and internet gateways',
      title_nl: 'Boundary firewalls and internet gateways',
      description: 'A boundary firewall or internet gateway must be installed between the internal network and the internet. The firewall must be configured to prevent unauthorised access to or from the internet.',
      description_nl: 'A boundary firewall or internet gateway must be installed between the internal network and the internet. The firewall must be configured to prevent unauthorised access to or from the internet.',
      category: 'Firewalls',
      subcategory: 'Boundary protection',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Deploy a firewall at every internet connection point. Configure rules to block all inbound connections by default, allowing only those that are required and documented.',
      verification_guidance: 'Review firewall configuration and rule sets. Verify no unnecessary inbound services are exposed.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '1.2',
      title: 'Default firewall password changed',
      title_nl: 'Default firewall password changed',
      description: 'The default administrative password on the firewall must be changed to something that is not easy to guess.',
      description_nl: 'The default administrative password on the firewall must be changed to something that is not easy to guess.',
      category: 'Firewalls',
      subcategory: 'Credential management',
      level: null,
      iso_mapping: 'A.9.4.3',
      implementation_guidance: 'Change all default administrative passwords on firewalls and network devices to strong, unique passwords during initial setup.',
      verification_guidance: 'Confirm default credentials cannot be used to access firewall administration.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '1.3',
      title: 'Firewall rules documented and approved',
      title_nl: 'Firewall rules documented and approved',
      description: 'Firewall rules allowing inbound network traffic must be approved and documented. Rules must be reviewed regularly to remove any rules that are no longer needed.',
      description_nl: 'Firewall rules allowing inbound network traffic must be approved and documented. Rules must be reviewed regularly to remove any rules that are no longer needed.',
      category: 'Firewalls',
      subcategory: 'Rule management',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Maintain a documented record of all firewall rules that allow inbound traffic. Include the business justification for each rule. Review rules at least annually.',
      verification_guidance: 'Request and review documentation of firewall rules. Verify each rule has a documented business justification.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    // 2. Secure Configuration
    {
      control_number: '2',
      title: 'Secure Configuration',
      title_nl: 'Secure Configuration',
      description: 'Computers and network devices must be configured to reduce the level of inherent vulnerabilities and provide only the services required to fulfil their role.',
      description_nl: 'Computers and network devices must be configured to reduce the level of inherent vulnerabilities and provide only the services required to fulfil their role.',
      category: 'Secure Configuration',
      subcategory: null,
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Remove or disable unnecessary software, user accounts, and services. Change default passwords. Enable host-based firewalls on devices where available.',
      verification_guidance: 'Audit systems for unnecessary software and services. Verify default credentials are changed. Check that auto-run and auto-play are disabled.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '2.1',
      title: 'Remove or disable unnecessary software',
      title_nl: 'Remove or disable unnecessary software',
      description: 'All unnecessary software, services, and functionality must be removed or disabled from devices in scope. Only software required for the business function should be installed.',
      description_nl: 'All unnecessary software, services, and functionality must be removed or disabled from devices in scope. Only software required for the business function should be installed.',
      category: 'Secure Configuration',
      subcategory: 'Software minimisation',
      level: null,
      iso_mapping: 'A.12.6.2',
      implementation_guidance: 'Maintain an approved software list. Remove any software not on the approved list. Disable auto-run and auto-play features.',
      verification_guidance: 'Review installed software against approved list. Verify auto-run features are disabled.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '2.2',
      title: 'Change default passwords',
      title_nl: 'Change default passwords',
      description: 'Default user accounts and passwords must be changed or removed. Where default accounts cannot be removed they must have complex passwords applied.',
      description_nl: 'Default user accounts and passwords must be changed or removed. Where default accounts cannot be removed they must have complex passwords applied.',
      category: 'Secure Configuration',
      subcategory: 'Credential management',
      level: null,
      iso_mapping: 'A.9.4.3',
      implementation_guidance: 'Identify all default user accounts and passwords. Change or remove them before deploying systems. Apply password complexity requirements.',
      verification_guidance: 'Test for default credentials. Verify password complexity rules are enforced.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    // 3. User Access Control
    {
      control_number: '3',
      title: 'User Access Control',
      title_nl: 'User Access Control',
      description: 'User accounts and access privileges must be controlled effectively. Access to data and services should only be granted to users who need it. Administrative accounts should only be used for administrative activities.',
      description_nl: 'User accounts and access privileges must be controlled effectively. Access to data and services should only be granted to users who need it. Administrative accounts should only be used for administrative activities.',
      category: 'User Access Control',
      subcategory: null,
      level: null,
      iso_mapping: 'A.9.2.1',
      implementation_guidance: 'Create individual user accounts for each user. Apply the principle of least privilege. Use separate administrator accounts for administrative tasks. Remove or disable user accounts when no longer required.',
      verification_guidance: 'Review user account list. Verify accounts follow the principle of least privilege. Check that leavers have had accounts disabled.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '3.1',
      title: 'User accounts controlled and managed',
      title_nl: 'User accounts controlled and managed',
      description: 'A process must exist to create and approve user accounts. Accounts must be removed or disabled when no longer required, or when staff leave the organisation.',
      description_nl: 'A process must exist to create and approve user accounts. Accounts must be removed or disabled when no longer required, or when staff leave the organisation.',
      category: 'User Access Control',
      subcategory: 'Account management',
      level: null,
      iso_mapping: 'A.9.2.1',
      implementation_guidance: 'Implement a formal user registration and deregistration process. Review user accounts regularly and disable dormant accounts.',
      verification_guidance: 'Review user provisioning process. Check for dormant or orphaned accounts.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '3.2',
      title: 'Administrative privileges restricted',
      title_nl: 'Administrative privileges restricted',
      description: 'Administrative accounts must only be used to perform administrative activities and not day-to-day user activities such as web browsing and accessing email.',
      description_nl: 'Administrative accounts must only be used to perform administrative activities and not day-to-day user activities such as web browsing and accessing email.',
      category: 'User Access Control',
      subcategory: 'Privilege management',
      level: null,
      iso_mapping: 'A.9.2.3',
      implementation_guidance: 'Provide separate accounts for administration and daily use. Restrict the number of administrative accounts. Do not use admin accounts for email or web browsing.',
      verification_guidance: 'Review admin account usage logs. Verify admin accounts are not used for routine tasks.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    // 4. Malware Protection
    {
      control_number: '4',
      title: 'Malware Protection',
      title_nl: 'Malware Protection',
      description: 'Malware (such as computer viruses) is software that has been written and distributed to perform malicious actions. Protection against malware must be implemented on all devices in scope.',
      description_nl: 'Malware (such as computer viruses) is software that has been written and distributed to perform malicious actions. Protection against malware must be implemented on all devices in scope.',
      category: 'Malware Protection',
      subcategory: null,
      level: null,
      iso_mapping: 'A.12.2.1',
      implementation_guidance: 'Install anti-malware software on all in-scope devices. Keep anti-malware definitions current. Configure regular scanning. Restrict execution of known malicious file types.',
      verification_guidance: 'Verify anti-malware is installed and running on all endpoints. Check that definitions are current.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '4.1',
      title: 'Anti-malware software installed and active',
      title_nl: 'Anti-malware software installed and active',
      description: 'Anti-malware software must be installed on all devices in scope and configured to stay up to date automatically. It must be set to scan files automatically on access, scan web pages during access, and prevent connections to malicious websites.',
      description_nl: 'Anti-malware software must be installed on all devices in scope and configured to stay up to date automatically. It must be set to scan files automatically on access, scan web pages during access, and prevent connections to malicious websites.',
      category: 'Malware Protection',
      subcategory: 'Anti-malware deployment',
      level: null,
      iso_mapping: 'A.12.2.1',
      implementation_guidance: 'Deploy anti-malware software with on-access scanning enabled. Enable automatic updates for signatures. Configure web filtering to block known malicious domains.',
      verification_guidance: 'Verify anti-malware software status on all endpoints. Check signature update dates.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '4.2',
      title: 'Application allow-listing or sandboxing',
      title_nl: 'Application allow-listing or sandboxing',
      description: 'As an alternative or complement to anti-malware software, organisations may implement application allow-listing to restrict which applications can run, or use application sandboxing to contain application behaviour.',
      description_nl: 'As an alternative or complement to anti-malware software, organisations may implement application allow-listing to restrict which applications can run, or use application sandboxing to contain application behaviour.',
      category: 'Malware Protection',
      subcategory: 'Application control',
      level: null,
      iso_mapping: 'A.12.6.2',
      implementation_guidance: 'Consider implementing application allow-listing to only permit approved applications to execute. Alternatively, use sandboxing to isolate untrusted applications.',
      verification_guidance: 'Review allow-list or sandbox policies. Test that unapproved applications are blocked.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    // 5. Security Update Management
    {
      control_number: '5',
      title: 'Security Update Management',
      title_nl: 'Security Update Management',
      description: 'Manufacturers and developers release regular updates (patches) to fix known vulnerabilities in their software. These updates must be applied promptly to protect against attacks that exploit known vulnerabilities.',
      description_nl: 'Manufacturers and developers release regular updates (patches) to fix known vulnerabilities in their software. These updates must be applied promptly to protect against attacks that exploit known vulnerabilities.',
      category: 'Security Update Management',
      subcategory: null,
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Apply security updates within 14 days of release for high-risk or critical vulnerabilities. Enable automatic updates where possible. Remove unsupported software.',
      verification_guidance: 'Verify patch levels on all in-scope devices. Check that automatic updates are enabled where available.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '5.1',
      title: 'Software kept up to date',
      title_nl: 'Software kept up to date',
      description: 'All software on in-scope devices must be licensed and supported. Security patches must be applied within 14 days of release where they fix vulnerabilities rated as critical or high risk.',
      description_nl: 'All software on in-scope devices must be licensed and supported. Security patches must be applied within 14 days of release where they fix vulnerabilities rated as critical or high risk.',
      category: 'Security Update Management',
      subcategory: 'Patch management',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Maintain a software inventory. Apply critical and high-risk patches within 14 days. Remove end-of-life software that no longer receives security updates.',
      verification_guidance: 'Review software versions and patch status. Verify no unsupported software is in use.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
    {
      control_number: '5.2',
      title: 'Unsupported software removed',
      title_nl: 'Unsupported software removed',
      description: 'Software that is no longer supported by its manufacturer or developer (and therefore no longer receives security updates) must be removed from all devices in scope.',
      description_nl: 'Software that is no longer supported by its manufacturer or developer (and therefore no longer receives security updates) must be removed from all devices in scope.',
      category: 'Security Update Management',
      subcategory: 'Software lifecycle',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Identify end-of-life software. Plan migration or replacement ahead of support end dates. Remove unsupported software promptly.',
      verification_guidance: 'Audit for unsupported operating systems and applications. Verify migration plans exist for approaching end-of-life software.',
      source_url: 'https://www.ncsc.gov.uk/cyberessentials/overview',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-ce.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
