// scripts/ingest-ncsc-zt.ts
// NCSC Zero Trust Architecture — 8 principles for zero trust networking
// Source: https://www.ncsc.gov.uk/collection/zero-trust-architecture
// Version: 2024

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-zt',
    name: 'NCSC Zero Trust Architecture',
    name_nl: 'NCSC Zero Trust Architecture',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: '8 principles for designing and deploying zero trust network architectures, where no implicit trust is granted to assets or user accounts based on their physical or network location',
    scope_sectors: ['government', 'defence', 'all'],
    structure_description: '8 zero trust principles covering identity, device health, policy enforcement, and monitoring for modern network architecture',
    source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    {
      control_number: '1',
      title: 'Know your architecture including users, devices, services and data',
      title_nl: 'Know your architecture including users, devices, services and data',
      description: 'In a zero trust architecture, you need to have a thorough understanding of your assets: who the users are, what devices are in use, what services are available, and where your data is stored. Maintaining an accurate, up-to-date inventory is foundational.',
      description_nl: 'In a zero trust architecture, you need to have a thorough understanding of your assets: who the users are, what devices are in use, what services are available, and where your data is stored. Maintaining an accurate, up-to-date inventory is foundational.',
      category: 'Architecture Foundations',
      subcategory: 'Asset inventory',
      level: null,
      iso_mapping: 'A.8.1.1',
      implementation_guidance: 'Maintain a dynamic inventory of all users, devices, services, and data stores. Automate discovery where possible. Classify assets by sensitivity and business function.',
      verification_guidance: 'Review asset inventory for completeness and currency. Verify automated discovery tools are deployed.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/know-your-architecture',
    },
    {
      control_number: '2',
      title: 'Know your user, service and device identities',
      title_nl: 'Know your user, service and device identities',
      description: 'Each user, service, and device should have a unique identity that can be used to authenticate them. Identity is a key signal in zero trust and forms the basis for policy decisions about access.',
      description_nl: 'Each user, service, and device should have a unique identity that can be used to authenticate them. Identity is a key signal in zero trust and forms the basis for policy decisions about access.',
      category: 'Identity',
      subcategory: 'Identity management',
      level: null,
      iso_mapping: 'A.9.2.1',
      implementation_guidance: 'Assign unique identities to all users, services, and devices. Use a central identity provider. Implement strong authentication including MFA. Manage the identity lifecycle (creation, modification, revocation).',
      verification_guidance: 'Review identity management processes. Verify all entities have unique identities. Check MFA enforcement.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/know-your-identities',
    },
    {
      control_number: '3',
      title: 'Assess user behaviour, service and device health',
      title_nl: 'Assess user behaviour, service and device health',
      description: 'Continuously assess the health and behaviour of devices and services, and the risk associated with user activities. Device health signals (patch level, configuration, compromise indicators) should inform access decisions dynamically.',
      description_nl: 'Continuously assess the health and behaviour of devices and services, and the risk associated with user activities. Device health signals (patch level, configuration, compromise indicators) should inform access decisions dynamically.',
      category: 'Health and Behaviour',
      subcategory: 'Continuous assessment',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Deploy endpoint detection and response (EDR) tools. Assess device compliance (patch level, encryption, configuration) before granting access. Monitor for anomalous user behaviour. Use device health signals in access decisions.',
      verification_guidance: 'Review device compliance assessment mechanisms. Verify health signals feed into access decisions.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/assess-behaviour-and-health',
    },
    {
      control_number: '4',
      title: 'Use policies to authorise requests',
      title_nl: 'Use policies to authorise requests',
      description: 'Every access request should be authorised against a policy. Policies should consider the identity, device health, context (location, time, risk score), and the sensitivity of the resource being accessed.',
      description_nl: 'Every access request should be authorised against a policy. Policies should consider the identity, device health, context (location, time, risk score), and the sensitivity of the resource being accessed.',
      category: 'Policy Enforcement',
      subcategory: 'Access policies',
      level: null,
      iso_mapping: 'A.9.4.1',
      implementation_guidance: 'Define access policies based on identity, device health, and context signals. Use a policy engine to evaluate requests dynamically. Implement deny-by-default posture.',
      verification_guidance: 'Review access policies for completeness. Verify policy engine is making dynamic decisions based on multiple signals.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/use-policies-to-authorise',
    },
    {
      control_number: '5',
      title: 'Authenticate and authorise everywhere',
      title_nl: 'Authenticate and authorise everywhere',
      description: 'Apply authentication and authorisation consistently across all services, regardless of whether the user is on the corporate network or connecting remotely. Internal network location does not confer trust.',
      description_nl: 'Apply authentication and authorisation consistently across all services, regardless of whether the user is on the corporate network or connecting remotely. Internal network location does not confer trust.',
      category: 'Policy Enforcement',
      subcategory: 'Consistent enforcement',
      level: null,
      iso_mapping: 'A.9.4.2',
      implementation_guidance: 'Require authentication for all service access regardless of network location. Remove implicit trust for internal networks. Apply the same security controls for on-premises and remote access.',
      verification_guidance: 'Test access controls from both internal and external networks. Verify no services are accessible without authentication.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/authenticate-and-authorise-everywhere',
    },
    {
      control_number: '6',
      title: 'Focus your monitoring on devices and services',
      title_nl: 'Focus your monitoring on devices and services',
      description: 'In a zero trust architecture, devices and services are more exposed than in a traditional network model. Monitoring should focus on device health, service health, and the security of connections between them.',
      description_nl: 'In a zero trust architecture, devices and services are more exposed than in a traditional network model. Monitoring should focus on device health, service health, and the security of connections between them.',
      category: 'Monitoring',
      subcategory: 'Device and service monitoring',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Deploy monitoring on all devices and services. Collect security telemetry from endpoints, identity systems, and service access logs. Correlate signals for threat detection.',
      verification_guidance: 'Review monitoring coverage. Verify telemetry is being collected from all key sources.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/focus-monitoring',
    },
    {
      control_number: '7',
      title: 'Do not trust the network, including the local network',
      title_nl: 'Do not trust the network, including the local network',
      description: 'The network should be treated as hostile. Communications between devices and services should be protected regardless of the network they traverse. This means encrypting traffic on local networks, not just over the internet.',
      description_nl: 'The network should be treated as hostile. Communications between devices and services should be protected regardless of the network they traverse. This means encrypting traffic on local networks, not just over the internet.',
      category: 'Network Security',
      subcategory: 'Network distrust',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Encrypt all network traffic, including on internal networks. Use mutual TLS between services. Do not rely on network segmentation as the primary security control.',
      verification_guidance: 'Test for unencrypted internal traffic. Verify mutual TLS between services. Check that VPN is not the sole access control.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/do-not-trust-the-network',
    },
    {
      control_number: '8',
      title: 'Choose services designed for zero trust',
      title_nl: 'Choose services designed for zero trust',
      description: 'Where possible, choose services and products that have been designed to work in a zero trust architecture. Services should support modern authentication protocols, expose health signals, and provide fine-grained access control.',
      description_nl: 'Where possible, choose services and products that have been designed to work in a zero trust architecture. Services should support modern authentication protocols, expose health signals, and provide fine-grained access control.',
      category: 'Architecture Foundations',
      subcategory: 'Service selection',
      level: null,
      iso_mapping: 'A.14.1.1',
      implementation_guidance: 'Evaluate services for zero trust compatibility during procurement. Require support for modern authentication (OIDC, SAML), fine-grained authorisation, and health signal exposure.',
      verification_guidance: 'Review procurement criteria for zero trust requirements. Verify deployed services support required capabilities.',
      source_url: 'https://www.ncsc.gov.uk/collection/zero-trust-architecture/zero-trust-principles/choose-services-for-zero-trust',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-zt.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
