// scripts/ingest-gds-servicestandard.ts
// GDS Service Standard — 14 points for digital government services
// Source: https://www.gov.uk/service-manual/service-standard
// Version: 2024

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'gds-servicestandard',
    name: 'GDS Service Standard',
    name_nl: 'GDS Service Standard',
    issuing_body: 'Government Digital Service (GDS)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: '14 points that teams building government services must meet. Services must pass government service assessments at alpha, beta, and live stages. Applies to all government transactional services.',
    scope_sectors: ['government'],
    structure_description: '14 numbered points covering user needs, team capability, agile methods, security, open standards, performance measurement, and accessibility for government digital services',
    source_url: 'https://www.gov.uk/service-manual/service-standard',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    {
      control_number: '1',
      title: 'Understand users and their needs',
      title_nl: 'Understand users and their needs',
      description: 'Develop a deep understanding of users and the problem you are trying to solve for them. Take time to understand the tasks users are trying to complete and the context they operate in.',
      description_nl: 'Develop a deep understanding of users and the problem you are trying to solve for them. Take time to understand the tasks users are trying to complete and the context they operate in.',
      category: 'Understanding Users',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Conduct user research with real users. Create user personas and journey maps. Validate assumptions with evidence. Include users with access needs in research.',
      verification_guidance: 'Review user research evidence. Verify research includes diverse user groups.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-1-understand-user-needs',
    },
    {
      control_number: '2',
      title: 'Solve a whole problem for users',
      title_nl: 'Solve a whole problem for users',
      description: 'Work towards solving a whole problem for users, collaborating across organisational boundaries where necessary. Consider the end-to-end journey, not just the digital part.',
      description_nl: 'Work towards solving a whole problem for users, collaborating across organisational boundaries where necessary. Consider the end-to-end journey, not just the digital part.',
      category: 'Understanding Users',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Map the end-to-end user journey. Identify pain points across the whole process. Work with other teams and organisations to address the complete journey.',
      verification_guidance: 'Review end-to-end journey maps. Verify cross-organisational collaboration where needed.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-2-solve-a-whole-problem',
    },
    {
      control_number: '3',
      title: 'Provide a joined up experience across all channels',
      title_nl: 'Provide a joined up experience across all channels',
      description: 'Work towards creating a service that meets users needs across all channels, including online, phone, and in person. Ensure the service works well for those who use each channel.',
      description_nl: 'Work towards creating a service that meets users needs across all channels, including online, phone, and in person. Ensure the service works well for those who use each channel.',
      category: 'Understanding Users',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Design for all channels users might use. Ensure assisted digital support is available. Test the service across channels.',
      verification_guidance: 'Review channel strategy. Verify assisted digital provision. Test cross-channel experience.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-3-join-up-across-channels',
    },
    {
      control_number: '4',
      title: 'Make the service simple to use',
      title_nl: 'Make the service simple to use',
      description: 'Build a service that is simple, intuitive, and comprehensible. Test it with users to make sure it works for them. Services should require the minimum possible steps to complete a task.',
      description_nl: 'Build a service that is simple, intuitive, and comprehensible. Test it with users to make sure it works for them. Services should require the minimum possible steps to complete a task.',
      category: 'Service Design',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Use the GOV.UK Design System. Minimise steps and decisions. Use plain language. Test usability with real users.',
      verification_guidance: 'Conduct usability testing. Review task completion rates. Check language clarity.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-4-make-the-service-simple-to-use',
    },
    {
      control_number: '5',
      title: 'Make sure everyone can use the service',
      title_nl: 'Make sure everyone can use the service',
      description: 'Provide a service that everyone can use, including disabled people and people with other legally protected characteristics. Meet accessibility standards (WCAG 2.1 AA) and test with assistive technologies.',
      description_nl: 'Provide a service that everyone can use, including disabled people and people with other legally protected characteristics. Meet accessibility standards (WCAG 2.1 AA) and test with assistive technologies.',
      category: 'Accessibility',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Meet WCAG 2.1 AA. Test with assistive technologies (screen readers, voice control). Include disabled users in research. Publish an accessibility statement.',
      verification_guidance: 'Run automated accessibility tests. Conduct manual testing with assistive technologies.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-5-make-sure-everyone-can-use-the-service',
    },
    {
      control_number: '6',
      title: 'Have a multidisciplinary team',
      title_nl: 'Have a multidisciplinary team',
      description: 'Put in place a sustainable multidisciplinary team that can design, build, operate, and continuously improve the service. The team should include or have access to the right skills.',
      description_nl: 'Put in place a sustainable multidisciplinary team that can design, build, operate, and continuously improve the service. The team should include or have access to the right skills.',
      category: 'Team',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Build a team with user research, design, development, operations, and subject matter expertise. Ensure the team can make decisions without excessive approvals.',
      verification_guidance: 'Review team composition. Verify required skills are present or accessible.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-6-have-a-multidisciplinary-team',
    },
    {
      control_number: '7',
      title: 'Use agile ways of working',
      title_nl: 'Use agile ways of working',
      description: 'Create the service using agile, iterative user-centred methods. Deliver working software early and often. Get regular feedback from users and iterate based on what you learn.',
      description_nl: 'Create the service using agile, iterative user-centred methods. Deliver working software early and often. Get regular feedback from users and iterate based on what you learn.',
      category: 'Ways of Working',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Use agile methods (Scrum, Kanban, or similar). Deliver in short iterations. Hold regular retrospectives. Respond to user feedback.',
      verification_guidance: 'Review delivery cadence. Check for regular user feedback loops. Verify iterative improvement.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-7-use-agile-ways-of-working',
    },
    {
      control_number: '8',
      title: 'Iterate and improve frequently',
      title_nl: 'Iterate and improve frequently',
      description: 'Make sure you have the capacity, resources, and technical flexibility to update and improve the service frequently. Work in small iterations. Release early, release often.',
      description_nl: 'Make sure you have the capacity, resources, and technical flexibility to update and improve the service frequently. Work in small iterations. Release early, release often.',
      category: 'Ways of Working',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Deploy frequently (weekly or more). Use feature flags for safe releases. Automate testing and deployment. Monitor service performance continuously.',
      verification_guidance: 'Review deployment frequency. Check automation coverage. Verify monitoring is in place.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-8-iterate-and-improve-frequently',
    },
    {
      control_number: '9',
      title: 'Create a secure service which protects users privacy',
      title_nl: 'Create a secure service which protects users privacy',
      description: 'Evaluate what data and information the service will be providing or storing, and address the security level, legal responsibilities, privacy issues, and risks associated with the service.',
      description_nl: 'Evaluate what data and information the service will be providing or storing, and address the security level, legal responsibilities, privacy issues, and risks associated with the service.',
      category: 'Security and Privacy',
      subcategory: null,
      level: null,
      iso_mapping: 'A.14.2.1',
      implementation_guidance: 'Conduct security assessments appropriate to the risk. Implement security from the start. Conduct DPIAs where required. Follow NCSC guidance.',
      verification_guidance: 'Review security assessments. Verify DPIA completion. Check NCSC guidance compliance.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-9-create-a-secure-service',
    },
    {
      control_number: '10',
      title: 'Define what success looks like and publish performance data',
      title_nl: 'Define what success looks like and publish performance data',
      description: 'Work out what success looks like for the service and identify metrics to tell you how the service is performing. Collect and report on the 4 mandatory KPIs: cost per transaction, user satisfaction, completion rate, and digital take-up.',
      description_nl: 'Work out what success looks like for the service and identify metrics to tell you how the service is performing. Collect and report on the 4 mandatory KPIs: cost per transaction, user satisfaction, completion rate, and digital take-up.',
      category: 'Performance',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Define success metrics. Implement analytics to track the 4 mandatory KPIs. Publish performance data on the performance platform.',
      verification_guidance: 'Verify KPI tracking is in place. Review published performance data.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-10-define-what-success-looks-like',
    },
    {
      control_number: '11',
      title: 'Choose the right tools and technology',
      title_nl: 'Choose the right tools and technology',
      description: 'Choose tools and technology that let you create a high quality service in a cost effective way. Minimise the cost of changing direction by choosing technology that is modular and aligned with open standards.',
      description_nl: 'Choose tools and technology that let you create a high quality service in a cost effective way. Minimise the cost of changing direction by choosing technology that is modular and aligned with open standards.',
      category: 'Technology',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Follow the Technology Code of Practice. Choose modular, standards-based technology. Evaluate total cost of ownership including exit costs.',
      verification_guidance: 'Review technology choices against the Technology Code of Practice. Check for vendor lock-in.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-11-choose-the-right-tools-and-technology',
    },
    {
      control_number: '12',
      title: 'Make new source code open',
      title_nl: 'Make new source code open',
      description: 'Make all new source code open and reusable, and publish it under appropriate licences. Demonstrate that you have considered any security concerns and taken mitigating action.',
      description_nl: 'Make all new source code open and reusable, and publish it under appropriate licences. Demonstrate that you have considered any security concerns and taken mitigating action.',
      category: 'Technology',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Publish code on GitHub or equivalent. Use MIT or Apache 2.0 licences. Review code for security issues before publishing. Document any code that cannot be published and why.',
      verification_guidance: 'Verify code is published. Check licence files. Review exceptions documentation.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-12-make-new-source-code-open',
    },
    {
      control_number: '13',
      title: 'Use and contribute to open standards, common components and patterns',
      title_nl: 'Use and contribute to open standards, common components and patterns',
      description: 'Build on open standards and common components and patterns from inside and outside government. Contribute back to open standards, components, and patterns you use.',
      description_nl: 'Build on open standards and common components and patterns from inside and outside government. Contribute back to open standards, components, and patterns you use.',
      category: 'Technology',
      subcategory: null,
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Use the GOV.UK Design System. Use government common platforms (Notify, Pay). Contribute improvements back to shared components.',
      verification_guidance: 'Review component usage. Check contributions to common platforms.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-13-use-common-standards-components-patterns',
    },
    {
      control_number: '14',
      title: 'Operate a reliable service',
      title_nl: 'Operate a reliable service',
      description: 'Minimise service downtime and have a plan to deal with it when it does happen. Maximise the availability of the service. Define and meet availability targets appropriate for the service.',
      description_nl: 'Minimise service downtime and have a plan to deal with it when it does happen. Maximise the availability of the service. Define and meet availability targets appropriate for the service.',
      category: 'Operations',
      subcategory: null,
      level: null,
      iso_mapping: 'A.17.1.1',
      implementation_guidance: 'Define availability targets. Implement monitoring and alerting. Create runbooks for common issues. Plan for disaster recovery. Test failover regularly.',
      verification_guidance: 'Review availability metrics against targets. Verify monitoring coverage. Check disaster recovery testing.',
      source_url: 'https://www.gov.uk/service-manual/service-standard/point-14-operate-a-reliable-service',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'gds-servicestandard.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
