// scripts/ingest-ncsc-board.ts
// NCSC Board Toolkit — 5 questions for board members about cybersecurity governance
// Source: https://www.ncsc.gov.uk/collection/board-toolkit

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-board',
    name: 'NCSC Board Toolkit',
    name_nl: 'NCSC Board Toolkit',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: '2023',
    effective_date: '2023-01-01',
    scope: 'Guidance and questions for board members and senior leaders to engage with cyber security governance effectively',
    scope_sectors: ['government', 'all'],
    structure_description: '5 board-level questions, each with discussion points and indicators of good practice for cyber security governance',
    source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    // Question 1
    {
      control_number: 'Q1',
      title: 'How do we defend our organisation against a cyber attack?',
      title_nl: 'How do we defend our organisation against a cyber attack?',
      description: 'Board members should understand the technical controls and processes in place to defend the organisation. This includes understanding the threat landscape, the defensive measures deployed, and how their effectiveness is measured.',
      description_nl: 'Board members should understand the technical controls and processes in place to defend the organisation. This includes understanding the threat landscape, the defensive measures deployed, and how their effectiveness is measured.',
      category: 'Board Governance',
      subcategory: 'Defence',
      level: null,
      iso_mapping: '5.1',
      implementation_guidance: 'Brief the board regularly on cyber defences. Include the current threat landscape, technical controls in place, and any gaps. Report on control effectiveness metrics.',
      verification_guidance: 'Review board reporting on cyber defences. Verify reports cover threats, controls, and effectiveness.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/how-do-we-defend',
    },
    {
      control_number: 'Q1.1',
      title: 'Threat landscape briefing',
      title_nl: 'Threat landscape briefing',
      description: 'The board receives regular briefings on the current cyber threat landscape relevant to the organisation sector and operations.',
      description_nl: 'The board receives regular briefings on the current cyber threat landscape relevant to the organisation sector and operations.',
      category: 'Board Governance',
      subcategory: 'Defence',
      level: null,
      iso_mapping: '6.1',
      implementation_guidance: 'Provide quarterly threat briefings to the board. Include sector-specific threats, incident trends, and NCSC advisories.',
      verification_guidance: 'Review board meeting minutes for threat briefings.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/how-do-we-defend',
    },
    {
      control_number: 'Q1.2',
      title: 'Technical controls understanding',
      title_nl: 'Technical controls understanding',
      description: 'The board has an appropriate level of understanding of the technical controls protecting the organisation, presented in business-relevant terms.',
      description_nl: 'The board has an appropriate level of understanding of the technical controls protecting the organisation, presented in business-relevant terms.',
      category: 'Board Governance',
      subcategory: 'Defence',
      level: null,
      iso_mapping: '5.1',
      implementation_guidance: 'Present technical controls to the board in non-technical language. Use risk-based metrics and business impact assessments.',
      verification_guidance: 'Review board reporting format for accessibility.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/how-do-we-defend',
    },
    // Question 2
    {
      control_number: 'Q2',
      title: 'How does the board make sure cyber risk is managed effectively?',
      title_nl: 'How does the board make sure cyber risk is managed effectively?',
      description: 'The board should assure itself that cyber risk is being managed as part of the wider risk management approach. This includes understanding how cyber risks are identified, assessed, and treated.',
      description_nl: 'The board should assure itself that cyber risk is being managed as part of the wider risk management approach. This includes understanding how cyber risks are identified, assessed, and treated.',
      category: 'Board Governance',
      subcategory: 'Risk Management',
      level: null,
      iso_mapping: '6.1',
      implementation_guidance: 'Integrate cyber risk into the enterprise risk register. Present cyber risks to the board in the same format as other business risks. Define risk appetite for cyber threats.',
      verification_guidance: 'Review the enterprise risk register for cyber risks. Verify risk appetite is defined.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/risk-management',
    },
    {
      control_number: 'Q2.1',
      title: 'Cyber risk on risk register',
      title_nl: 'Cyber risk on risk register',
      description: 'Cyber security risks are included in the organisation enterprise risk register and reviewed by the board regularly.',
      description_nl: 'Cyber security risks are included in the organisation enterprise risk register and reviewed by the board regularly.',
      category: 'Board Governance',
      subcategory: 'Risk Management',
      level: null,
      iso_mapping: '6.1',
      implementation_guidance: 'Add cyber risks to the enterprise risk register. Review them at every board risk committee meeting.',
      verification_guidance: 'Check enterprise risk register for cyber entries. Review board risk committee minutes.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/risk-management',
    },
    // Question 3
    {
      control_number: 'Q3',
      title: 'How do we make sure our staff support our cyber resilience?',
      title_nl: 'How do we make sure our staff support our cyber resilience?',
      description: 'People are both the strongest defence and the weakest link. The board should understand how the organisation develops a positive security culture and ensures staff have the awareness and skills to protect the organisation.',
      description_nl: 'People are both the strongest defence and the weakest link. The board should understand how the organisation develops a positive security culture and ensures staff have the awareness and skills to protect the organisation.',
      category: 'Board Governance',
      subcategory: 'People',
      level: null,
      iso_mapping: 'A.7.2.2',
      implementation_guidance: 'Report to the board on security training completion rates and effectiveness. Measure security culture through surveys and phishing simulations.',
      verification_guidance: 'Review board reports on security culture and training metrics.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/people',
    },
    {
      control_number: 'Q3.1',
      title: 'Security culture measurement',
      title_nl: 'Security culture measurement',
      description: 'The organisation measures and reports on security culture, including training completion, phishing simulation results, and incident reporting rates.',
      description_nl: 'The organisation measures and reports on security culture, including training completion, phishing simulation results, and incident reporting rates.',
      category: 'Board Governance',
      subcategory: 'People',
      level: null,
      iso_mapping: 'A.7.2.2',
      implementation_guidance: 'Track security culture metrics. Report to the board quarterly. Benchmark against sector averages where available.',
      verification_guidance: 'Review security culture metrics reports.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/people',
    },
    // Question 4
    {
      control_number: 'Q4',
      title: 'How do we make sure our partners and suppliers protect our data?',
      title_nl: 'How do we make sure our partners and suppliers protect our data?',
      description: 'The board should understand how the organisation manages supply chain cyber risk. Third-party access to systems and data creates risk that must be managed through contracts, due diligence, and ongoing monitoring.',
      description_nl: 'The board should understand how the organisation manages supply chain cyber risk. Third-party access to systems and data creates risk that must be managed through contracts, due diligence, and ongoing monitoring.',
      category: 'Board Governance',
      subcategory: 'Supply Chain',
      level: null,
      iso_mapping: 'A.15.1.1',
      implementation_guidance: 'Report to the board on key suppliers and their security posture. Include supply chain risks in the risk register. Verify supplier security through contractual requirements and assurance.',
      verification_guidance: 'Review board reports on supply chain security. Check supplier assurance records.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/supply-chain',
    },
    {
      control_number: 'Q4.1',
      title: 'Supply chain risk reporting',
      title_nl: 'Supply chain risk reporting',
      description: 'The board receives regular reports on supply chain cyber risks, including the security posture of critical suppliers.',
      description_nl: 'The board receives regular reports on supply chain cyber risks, including the security posture of critical suppliers.',
      category: 'Board Governance',
      subcategory: 'Supply Chain',
      level: null,
      iso_mapping: 'A.15.2.1',
      implementation_guidance: 'Include supply chain risk in board reporting. Report on critical supplier assessments and any identified issues.',
      verification_guidance: 'Review board reports for supply chain content.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/supply-chain',
    },
    // Question 5
    {
      control_number: 'Q5',
      title: 'What do we do when we have a cyber incident?',
      title_nl: 'What do we do when we have a cyber incident?',
      description: 'The board should be confident that the organisation can respond effectively to a cyber incident. This includes having tested plans, clear roles, and external support arrangements in place.',
      description_nl: 'The board should be confident that the organisation can respond effectively to a cyber incident. This includes having tested plans, clear roles, and external support arrangements in place.',
      category: 'Board Governance',
      subcategory: 'Incident Response',
      level: null,
      iso_mapping: 'A.16.1.1',
      implementation_guidance: 'Brief the board on the incident response plan. Include the board communication role during major incidents. Conduct board-level tabletop exercises.',
      verification_guidance: 'Review incident response plan for board involvement. Check exercise records.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/incident-management',
    },
    {
      control_number: 'Q5.1',
      title: 'Board incident response role',
      title_nl: 'Board incident response role',
      description: 'The board understands its role during a major cyber incident, including communications, decision-making authority, and regulatory notification obligations.',
      description_nl: 'The board understands its role during a major cyber incident, including communications, decision-making authority, and regulatory notification obligations.',
      category: 'Board Governance',
      subcategory: 'Incident Response',
      level: null,
      iso_mapping: 'A.16.1.1',
      implementation_guidance: 'Define the board communication plan for major incidents. Include regulatory notification requirements (ICO, sector regulators). Conduct board-level exercises.',
      verification_guidance: 'Review board incident communication plan. Verify board exercises have been conducted.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/incident-management',
    },
    {
      control_number: 'Q5.2',
      title: 'Incident response plan tested',
      title_nl: 'Incident response plan tested',
      description: 'The incident response plan has been tested through exercises that include board-level participation, and lessons learned have been acted upon.',
      description_nl: 'The incident response plan has been tested through exercises that include board-level participation, and lessons learned have been acted upon.',
      category: 'Board Governance',
      subcategory: 'Incident Response',
      level: null,
      iso_mapping: 'A.16.1.5',
      implementation_guidance: 'Conduct at least annual tabletop exercises with board participation. Document lessons learned and track improvement actions.',
      verification_guidance: 'Review exercise records and improvement tracking.',
      source_url: 'https://www.ncsc.gov.uk/collection/board-toolkit/incident-management',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-board.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
