// scripts/ingest-gds-techcode.ts
// GDS Technology Code of Practice — 12 points for government technology
// Source: https://www.gov.uk/guidance/the-technology-code-of-practice
// Version: 2021

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'gds-techcode',
    name: 'GDS Technology Code of Practice',
    name_nl: 'GDS Technology Code of Practice',
    issuing_body: 'Government Digital Service (GDS)',
    version: '2021',
    effective_date: '2021-01-01',
    scope: '12-point code of practice that sets the standard for government technology. All government departments must follow this code when spending on technology or making significant changes to technology services.',
    scope_sectors: ['government'],
    structure_description: '12 numbered points covering user needs, accessibility, open standards, cloud hosting, security, and data management for government technology',
    source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    {
      control_number: '1',
      title: 'Define user needs',
      title_nl: 'Define user needs',
      description: 'Understand your users and their needs. Do research to develop a deep knowledge of who the service users are and what that means for the design of the service. Build the service based on evidence of user needs.',
      description_nl: 'Understand your users and their needs. Do research to develop a deep knowledge of who the service users are and what that means for the design of the service. Build the service based on evidence of user needs.',
      category: 'User-Centred Design',
      subcategory: 'User research',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Conduct user research before and during service development. Base design decisions on evidence of user needs. Validate designs with real users through usability testing.',
      verification_guidance: 'Review user research evidence. Verify design decisions trace to identified user needs.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#define-user-needs',
    },
    {
      control_number: '2',
      title: 'Make things accessible and inclusive',
      title_nl: 'Make things accessible and inclusive',
      description: 'Make sure your technology, infrastructure, and systems are accessible and inclusive for all users. Meet accessibility standards for public-facing services (WCAG 2.1 AA minimum) and consider the needs of all users including those with disabilities.',
      description_nl: 'Make sure your technology, infrastructure, and systems are accessible and inclusive for all users. Meet accessibility standards for public-facing services (WCAG 2.1 AA minimum) and consider the needs of all users including those with disabilities.',
      category: 'User-Centred Design',
      subcategory: 'Accessibility',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Design for accessibility from the start. Meet WCAG 2.1 AA standard at minimum. Test with assistive technologies. Publish an accessibility statement.',
      verification_guidance: 'Conduct accessibility testing. Verify WCAG 2.1 AA compliance. Review accessibility statement.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#make-things-accessible',
    },
    {
      control_number: '3',
      title: 'Be open and use open source',
      title_nl: 'Be open and use open source',
      description: 'Publish your code and use open source to improve transparency, flexibility, and accountability. Use open standards to avoid lock-in. Make all new source code open by default.',
      description_nl: 'Publish your code and use open source to improve transparency, flexibility, and accountability. Use open standards to avoid lock-in. Make all new source code open by default.',
      category: 'Open Standards',
      subcategory: 'Open source',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Publish source code openly where possible. Use open source software where it is appropriate. Choose open standards over proprietary formats. Document any exceptions where code cannot be published.',
      verification_guidance: 'Verify source code is published. Review open source usage. Check for proprietary lock-in.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#be-open-and-use-open-source',
    },
    {
      control_number: '4',
      title: 'Make use of open standards',
      title_nl: 'Make use of open standards',
      description: 'Use open standards to build government technology that works across different systems and services. This makes sharing data between systems easier and avoids vendor lock-in.',
      description_nl: 'Use open standards to build government technology that works across different systems and services. This makes sharing data between systems easier and avoids vendor lock-in.',
      category: 'Open Standards',
      subcategory: 'Interoperability',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Use open standards listed in the Open Standards Principles. Ensure data formats and APIs use open standards. Avoid proprietary protocols where open alternatives exist.',
      verification_guidance: 'Review data formats and APIs for open standards compliance. Check for proprietary dependencies.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#make-use-of-open-standards',
    },
    {
      control_number: '5',
      title: 'Use cloud first',
      title_nl: 'Use cloud first',
      description: 'Use public cloud first as stated in the government Cloud First policy. Consider SaaS before PaaS, and PaaS before IaaS. Only use private cloud or on-premises hosting if there is a specific reason why public cloud cannot meet the requirement.',
      description_nl: 'Use public cloud first as stated in the government Cloud First policy. Consider SaaS before PaaS, and PaaS before IaaS. Only use private cloud or on-premises hosting if there is a specific reason why public cloud cannot meet the requirement.',
      category: 'Infrastructure',
      subcategory: 'Cloud hosting',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Evaluate public cloud options first for all new services. Document the reason if public cloud is not selected. Use the G-Cloud framework for procurement. Ensure cloud services meet security standards.',
      verification_guidance: 'Review hosting decisions for cloud-first compliance. Verify exceptions are documented and justified.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#use-cloud-first',
    },
    {
      control_number: '6',
      title: 'Make things secure',
      title_nl: 'Make things secure',
      description: 'Keep systems and data safe with the appropriate level of security. Design services with security from the start. Apply the NCSC security design principles and meet the Minimum Cyber Security Standard.',
      description_nl: 'Keep systems and data safe with the appropriate level of security. Design services with security from the start. Apply the NCSC security design principles and meet the Minimum Cyber Security Standard.',
      category: 'Security',
      subcategory: 'Security by design',
      level: null,
      iso_mapping: 'A.14.2.1',
      implementation_guidance: 'Apply security from the start of service design. Follow NCSC guidance. Meet the Minimum Cyber Security Standard. Conduct security assessments. Obtain appropriate accreditation.',
      verification_guidance: 'Verify security is addressed in design documentation. Check compliance with Minimum Cyber Security Standard.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#make-things-secure',
    },
    {
      control_number: '7',
      title: 'Make privacy integral',
      title_nl: 'Make privacy integral',
      description: 'Make sure users rights are protected by integrating privacy into system design. Conduct Data Protection Impact Assessments (DPIAs) where required. Comply with UK GDPR and the Data Protection Act 2018.',
      description_nl: 'Make sure users rights are protected by integrating privacy into system design. Conduct Data Protection Impact Assessments (DPIAs) where required. Comply with UK GDPR and the Data Protection Act 2018.',
      category: 'Data Management',
      subcategory: 'Privacy by design',
      level: null,
      iso_mapping: 'A.18.1.4',
      implementation_guidance: 'Conduct DPIAs for services processing personal data. Minimise data collection. Implement privacy controls. Appoint a Data Protection Officer where required.',
      verification_guidance: 'Review DPIAs. Verify data minimisation. Check privacy controls implementation.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#make-privacy-integral',
    },
    {
      control_number: '8',
      title: 'Share, reuse and collaborate',
      title_nl: 'Share, reuse and collaborate',
      description: 'Avoid duplication and unnecessary costs by sharing and reusing technology, data, and services across government. Use common platforms and services where they exist (GOV.UK Notify, Pay, etc.).',
      description_nl: 'Avoid duplication and unnecessary costs by sharing and reusing technology, data, and services across government. Use common platforms and services where they exist (GOV.UK Notify, Pay, etc.).',
      category: 'Collaboration',
      subcategory: 'Reuse',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Check for existing government platforms and services before building new ones. Use GOV.UK common platforms (Notify, Pay, Verify). Share code and patterns with other departments.',
      verification_guidance: 'Verify reuse assessment was conducted. Check usage of common platforms.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#share-reuse-and-collaborate',
    },
    {
      control_number: '9',
      title: 'Integrate and adapt technology',
      title_nl: 'Integrate and adapt technology',
      description: 'Your technology should work with existing services and infrastructure. Use APIs and standard integration patterns. Plan for technology to be replaceable — avoid building systems that cannot be changed.',
      description_nl: 'Your technology should work with existing services and infrastructure. Use APIs and standard integration patterns. Plan for technology to be replaceable — avoid building systems that cannot be changed.',
      category: 'Architecture',
      subcategory: 'Integration',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Design systems with APIs for integration. Use standard patterns and protocols. Ensure components can be replaced independently. Document integration points.',
      verification_guidance: 'Review system architecture for integration capability. Verify API availability. Check component replaceability.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#integrate-and-adapt-technology',
    },
    {
      control_number: '10',
      title: 'Make better use of data',
      title_nl: 'Make better use of data',
      description: 'Use data to inform decisions and improve services. Make data available for reuse where appropriate, following the government API standards. Maintain data quality and manage data as an asset.',
      description_nl: 'Use data to inform decisions and improve services. Make data available for reuse where appropriate, following the government API standards. Maintain data quality and manage data as an asset.',
      category: 'Data Management',
      subcategory: 'Data governance',
      level: null,
      iso_mapping: 'A.8.2.1',
      implementation_guidance: 'Treat data as an asset. Publish open data where possible. Follow government API standards. Implement data quality controls. Use data to improve services.',
      verification_guidance: 'Review data governance practices. Check data quality metrics. Verify API standards compliance.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#make-better-use-of-data',
    },
    {
      control_number: '11',
      title: 'Define your purchasing strategy',
      title_nl: 'Define your purchasing strategy',
      description: 'Your purchasing strategy must be in line with the Technology Code of Practice. Use government frameworks (G-Cloud, Digital Outcomes and Specialists). Avoid large, long-term contracts that limit flexibility.',
      description_nl: 'Your purchasing strategy must be in line with the Technology Code of Practice. Use government frameworks (G-Cloud, Digital Outcomes and Specialists). Avoid large, long-term contracts that limit flexibility.',
      category: 'Procurement',
      subcategory: 'Purchasing strategy',
      level: null,
      iso_mapping: 'A.15.1.1',
      implementation_guidance: 'Use government procurement frameworks. Break contracts into smaller components. Avoid vendor lock-in. Include exit clauses and data portability requirements.',
      verification_guidance: 'Review procurement approach. Verify framework usage. Check contract terms for lock-in risks.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#define-your-purchasing-strategy',
    },
    {
      control_number: '12',
      title: 'Meet the Service Standard',
      title_nl: 'Meet the Service Standard',
      description: 'If you are building a service as part of the technology change, it should meet the Service Standard. Services must pass government service assessments at alpha, beta, and live stages.',
      description_nl: 'If you are building a service as part of the technology change, it should meet the Service Standard. Services must pass government service assessments at alpha, beta, and live stages.',
      category: 'Service Design',
      subcategory: 'Service Standard compliance',
      level: null,
      iso_mapping: null,
      implementation_guidance: 'Design services to meet the Service Standard from the outset. Plan for service assessments at each stage. Address assessment feedback before progressing.',
      verification_guidance: 'Verify service assessment results. Check Service Standard compliance at each stage.',
      source_url: 'https://www.gov.uk/guidance/the-technology-code-of-practice#meet-the-service-standard',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'gds-techcode.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
