// scripts/ingest-ncsc-caf.ts
// NCSC Cyber Assessment Framework (CAF) — 4 objectives, 14 principles, ~39 contributing outcomes
// Source: https://www.ncsc.gov.uk/collection/caf
// Version: 3.2 (2024)

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-caf',
    name: 'Cyber Assessment Framework',
    name_nl: 'Cyber Assessment Framework',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: '3.2',
    effective_date: '2024-04-01',
    scope: 'Assessment of cyber resilience for operators of essential services (OES) and relevant digital service providers under NIS Regulations',
    scope_sectors: ['government', 'energy', 'transport', 'healthcare', 'water', 'digital_infrastructure'],
    structure_description: '4 objectives (A-D), 14 principles, each with contributing outcomes that define the expected security posture',
    source_url: 'https://www.ncsc.gov.uk/collection/caf',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    // Objective A: Managing Security Risk
    // A1 Governance
    {
      control_number: 'A1.a',
      title: 'Board direction',
      title_nl: 'Board direction',
      description: 'The organisation has a board-level individual or committee with responsibility for the security of network and information systems. Security-related decisions are made with appropriate authority, informed by an understanding of relevant risks.',
      description_nl: 'The organisation has a board-level individual or committee with responsibility for the security of network and information systems. Security-related decisions are made with appropriate authority, informed by an understanding of relevant risks.',
      category: 'Managing Security Risk',
      subcategory: 'A1 Governance',
      level: null,
      iso_mapping: '5.1',
      implementation_guidance: 'Appoint a named board member or committee responsible for cyber security. Ensure security is a regular agenda item at board meetings. Provide the board with reporting on security risks and incidents.',
      verification_guidance: 'Confirm board-level accountability for cyber security exists. Review board meeting minutes for security agenda items.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-1-governance',
    },
    {
      control_number: 'A1.b',
      title: 'Roles and responsibilities',
      title_nl: 'Roles and responsibilities',
      description: 'The organisation has established roles and responsibilities for the security of network and information systems at all levels, with clear ownership and accountability.',
      description_nl: 'The organisation has established roles and responsibilities for the security of network and information systems at all levels, with clear ownership and accountability.',
      category: 'Managing Security Risk',
      subcategory: 'A1 Governance',
      level: null,
      iso_mapping: '5.2',
      implementation_guidance: 'Define and document security roles and responsibilities across the organisation. Assign security ownership for systems and data. Ensure adequate resourcing for security functions.',
      verification_guidance: 'Review security role definitions and assignments. Verify adequate staffing and budget allocation.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-1-governance',
    },
    {
      control_number: 'A1.c',
      title: 'Decision-making',
      title_nl: 'Decision-making',
      description: 'Appropriate organisational structures and processes are in place to understand, assess and systematically manage security risks to the network and information systems that support essential functions.',
      description_nl: 'Appropriate organisational structures and processes are in place to understand, assess and systematically manage security risks to the network and information systems that support essential functions.',
      category: 'Managing Security Risk',
      subcategory: 'A1 Governance',
      level: null,
      iso_mapping: '5.1',
      implementation_guidance: 'Establish a risk management framework that integrates cyber security. Define decision-making processes for accepting, mitigating, or transferring security risks.',
      verification_guidance: 'Review risk management framework and decision records. Verify risk appetite is defined and communicated.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-1-governance',
    },
    // A2 Risk Management
    {
      control_number: 'A2.a',
      title: 'Risk management process',
      title_nl: 'Risk management process',
      description: 'The organisation has an effective and well-established risk management process that identifies, assesses and records risks to the security of network and information systems, and addresses them proportionately and systematically.',
      description_nl: 'The organisation has an effective and well-established risk management process that identifies, assesses and records risks to the security of network and information systems, and addresses them proportionately and systematically.',
      category: 'Managing Security Risk',
      subcategory: 'A2 Risk Management',
      level: null,
      iso_mapping: '6.1',
      implementation_guidance: 'Implement a documented risk management process covering identification, assessment, treatment, and review of cyber security risks. Maintain a risk register.',
      verification_guidance: 'Review the risk management process documentation and risk register. Verify risks are regularly reviewed and updated.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-2-risk-management',
    },
    {
      control_number: 'A2.b',
      title: 'Assurance',
      title_nl: 'Assurance',
      description: 'The organisation has appropriate assurance activities to verify that the security measures protecting network and information systems are effective and remain appropriate.',
      description_nl: 'The organisation has appropriate assurance activities to verify that the security measures protecting network and information systems are effective and remain appropriate.',
      category: 'Managing Security Risk',
      subcategory: 'A2 Risk Management',
      level: null,
      iso_mapping: '9.2',
      implementation_guidance: 'Conduct regular security assessments and audits. Include penetration testing, vulnerability scanning, and configuration reviews. Review assurance findings and track remediation.',
      verification_guidance: 'Review audit and assessment reports. Verify remediation actions are tracked and completed.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-2-risk-management',
    },
    // A3 Asset Management
    {
      control_number: 'A3.a',
      title: 'Asset management',
      title_nl: 'Asset management',
      description: 'Everything required to deliver, maintain, or support networks and information systems that are necessary for the operation of essential functions is determined and understood. This includes data, people, and systems as well as any supporting infrastructure.',
      description_nl: 'Everything required to deliver, maintain, or support networks and information systems that are necessary for the operation of essential functions is determined and understood. This includes data, people, and systems as well as any supporting infrastructure.',
      category: 'Managing Security Risk',
      subcategory: 'A3 Asset Management',
      level: null,
      iso_mapping: 'A.8.1.1',
      implementation_guidance: 'Maintain an up-to-date inventory of all assets supporting essential functions, including hardware, software, data, and network components. Classify assets based on their importance.',
      verification_guidance: 'Review asset inventory for completeness and accuracy. Verify classification is applied consistently.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-3-asset-management',
    },
    // A4 Supply Chain
    {
      control_number: 'A4.a',
      title: 'Supply chain',
      title_nl: 'Supply chain',
      description: 'The organisation understands and manages security risks to networks and information systems that arise from dependencies on external suppliers. This includes ensuring that appropriate measures are employed where third-party services are used.',
      description_nl: 'The organisation understands and manages security risks to networks and information systems that arise from dependencies on external suppliers. This includes ensuring that appropriate measures are employed where third-party services are used.',
      category: 'Managing Security Risk',
      subcategory: 'A4 Supply Chain',
      level: null,
      iso_mapping: 'A.15.1.1',
      implementation_guidance: 'Maintain a register of key suppliers. Include security requirements in contracts. Conduct due diligence and ongoing assurance of supplier security practices.',
      verification_guidance: 'Review supplier register and contracts. Verify security requirements are included and supplier compliance is monitored.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/a-4-supply-chain',
    },
    // Objective B: Protecting Against Cyber Attack
    // B1 Service Protection Policies and Processes
    {
      control_number: 'B1.a',
      title: 'Policy and process development',
      title_nl: 'Policy and process development',
      description: 'The organisation defines, implements, communicates and enforces appropriate policies for securing the network and information systems that support the operation of essential functions.',
      description_nl: 'The organisation defines, implements, communicates and enforces appropriate policies for securing the network and information systems that support the operation of essential functions.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B1 Service Protection Policies',
      level: null,
      iso_mapping: '5.2',
      implementation_guidance: 'Develop security policies covering acceptable use, access control, incident management, change management, and business continuity. Communicate policies to all staff.',
      verification_guidance: 'Review security policy documents. Verify policies are communicated, understood, and enforced.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-1-service-protection-policies-and-processes',
    },
    {
      control_number: 'B1.b',
      title: 'Policy and process implementation',
      title_nl: 'Policy and process implementation',
      description: 'Security policies and processes are effectively implemented across the organisation, with compliance monitored and non-compliance addressed.',
      description_nl: 'Security policies and processes are effectively implemented across the organisation, with compliance monitored and non-compliance addressed.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B1 Service Protection Policies',
      level: null,
      iso_mapping: '5.2',
      implementation_guidance: 'Put mechanisms in place to monitor compliance with security policies. Address non-compliance through training, enforcement, or technical controls.',
      verification_guidance: 'Review compliance monitoring records. Check that policy violations are tracked and addressed.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-1-service-protection-policies-and-processes',
    },
    // B2 Identity and Access Control
    {
      control_number: 'B2.a',
      title: 'Identity verification, authentication and authorisation',
      title_nl: 'Identity verification, authentication and authorisation',
      description: 'The organisation verifies the identity of users and systems and manages access to services, data, and operational technology based on appropriate policies. Strongly protected authentication is used to control access.',
      description_nl: 'The organisation verifies the identity of users and systems and manages access to services, data, and operational technology based on appropriate policies. Strongly protected authentication is used to control access.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B2 Identity and Access Control',
      level: null,
      iso_mapping: 'A.9.2.1',
      implementation_guidance: 'Implement multi-factor authentication for privileged access. Apply the principle of least privilege. Regularly review user access rights. Disable inactive accounts promptly.',
      verification_guidance: 'Review access control policies and implementation. Verify MFA is enforced for privileged access.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-2-identity-and-access-control',
    },
    {
      control_number: 'B2.b',
      title: 'Device management',
      title_nl: 'Device management',
      description: 'Appropriate policies and processes are in place to manage devices that have access to the network and information systems. Devices are configured securely and maintained throughout their lifecycle.',
      description_nl: 'Appropriate policies and processes are in place to manage devices that have access to the network and information systems. Devices are configured securely and maintained throughout their lifecycle.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B2 Identity and Access Control',
      level: null,
      iso_mapping: 'A.8.1.1',
      implementation_guidance: 'Maintain an inventory of all devices. Apply secure configuration standards. Manage device lifecycle including provisioning, patching, and decommissioning.',
      verification_guidance: 'Review device inventory and configuration baselines. Verify patching is up to date.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-2-identity-and-access-control',
    },
    {
      control_number: 'B2.c',
      title: 'Privileged user management',
      title_nl: 'Privileged user management',
      description: 'The organisation closely manages privileged access to network and information systems. Privileged user activities are monitored, and privileges are reviewed regularly.',
      description_nl: 'The organisation closely manages privileged access to network and information systems. Privileged user activities are monitored, and privileges are reviewed regularly.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B2 Identity and Access Control',
      level: null,
      iso_mapping: 'A.9.2.3',
      implementation_guidance: 'Restrict the number of privileged accounts. Use privileged access management (PAM) tools. Log all privileged user activities. Review privileged access rights quarterly.',
      verification_guidance: 'Review privileged account inventory. Verify logging of privileged actions. Check frequency of access reviews.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-2-identity-and-access-control',
    },
    // B3 Data Security
    {
      control_number: 'B3.a',
      title: 'Understanding data',
      title_nl: 'Understanding data',
      description: 'The organisation understands the data stored in, or transmitted by, its network and information systems. Data at rest and data in transit is protected from actions that may compromise the confidentiality, integrity, or availability of the essential function.',
      description_nl: 'The organisation understands the data stored in, or transmitted by, its network and information systems. Data at rest and data in transit is protected from actions that may compromise the confidentiality, integrity, or availability of the essential function.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B3 Data Security',
      level: null,
      iso_mapping: 'A.8.2.1',
      implementation_guidance: 'Classify data according to sensitivity and business impact. Implement encryption for data in transit and at rest. Apply appropriate access controls based on data classification.',
      verification_guidance: 'Review data classification scheme and implementation. Verify encryption is applied where required.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-3-data-security',
    },
    {
      control_number: 'B3.b',
      title: 'Data in transit',
      title_nl: 'Data in transit',
      description: 'Data in transit is appropriately protected. The organisation has confidence that the protections applied to data in transit are suitably robust.',
      description_nl: 'Data in transit is appropriately protected. The organisation has confidence that the protections applied to data in transit are suitably robust.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B3 Data Security',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Use TLS 1.2 or later for data in transit. Implement VPNs or other encryption for network connections carrying sensitive data.',
      verification_guidance: 'Check TLS configurations on all services. Verify network encryption for sensitive data flows.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-3-data-security',
    },
    {
      control_number: 'B3.c',
      title: 'Stored data',
      title_nl: 'Stored data',
      description: 'Stored data is appropriately protected. Data at rest is secured against unauthorised access, modification, or deletion.',
      description_nl: 'Stored data is appropriately protected. Data at rest is secured against unauthorised access, modification, or deletion.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B3 Data Security',
      level: null,
      iso_mapping: 'A.8.2.3',
      implementation_guidance: 'Apply encryption to sensitive data at rest. Implement access controls to restrict data access to authorised users. Maintain secure backups.',
      verification_guidance: 'Review encryption implementation for stored data. Verify backup procedures and access controls.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-3-data-security',
    },
    {
      control_number: 'B3.d',
      title: 'Mobile data',
      title_nl: 'Mobile data',
      description: 'The organisation has appropriate measures to protect data accessed from, or stored on, mobile devices.',
      description_nl: 'The organisation has appropriate measures to protect data accessed from, or stored on, mobile devices.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B3 Data Security',
      level: null,
      iso_mapping: 'A.6.2.1',
      implementation_guidance: 'Implement mobile device management (MDM). Require encryption on mobile devices. Apply remote wipe capability for lost or stolen devices.',
      verification_guidance: 'Verify MDM enrolment coverage. Check encryption status on mobile devices.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-3-data-security',
    },
    {
      control_number: 'B3.e',
      title: 'Media and equipment sanitisation',
      title_nl: 'Media and equipment sanitisation',
      description: 'The organisation has appropriate policies and processes for sanitising media and equipment before disposal or re-use.',
      description_nl: 'The organisation has appropriate policies and processes for sanitising media and equipment before disposal or re-use.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B3 Data Security',
      level: null,
      iso_mapping: 'A.8.3.2',
      implementation_guidance: 'Define data destruction policies for different media types. Use approved sanitisation methods. Maintain records of disposed equipment.',
      verification_guidance: 'Review disposal records. Verify sanitisation methods align with data sensitivity.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-3-data-security',
    },
    // B4 System Security
    {
      control_number: 'B4.a',
      title: 'Secure by design',
      title_nl: 'Secure by design',
      description: 'Network and information systems are designed to be secure. Security is considered at all stages of the system lifecycle, including design, build, testing, deployment, and decommissioning.',
      description_nl: 'Network and information systems are designed to be secure. Security is considered at all stages of the system lifecycle, including design, build, testing, deployment, and decommissioning.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B4 System Security',
      level: null,
      iso_mapping: 'A.14.2.1',
      implementation_guidance: 'Apply secure design principles. Conduct security architecture reviews. Use hardened build standards. Perform security testing before deployment.',
      verification_guidance: 'Review design documentation for security considerations. Verify hardened build standards are applied.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-4-system-security',
    },
    {
      control_number: 'B4.b',
      title: 'Secure configuration',
      title_nl: 'Secure configuration',
      description: 'The organisation securely configures its network and information systems in accordance with documented policies and processes. Configuration is managed and maintained throughout the system lifecycle.',
      description_nl: 'The organisation securely configures its network and information systems in accordance with documented policies and processes. Configuration is managed and maintained throughout the system lifecycle.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B4 System Security',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Define and apply baseline security configurations. Use configuration management tools. Monitor for configuration drift. Document and approve all configuration changes.',
      verification_guidance: 'Review baseline configurations. Verify change management process for configuration changes.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-4-system-security',
    },
    {
      control_number: 'B4.c',
      title: 'Secure management',
      title_nl: 'Secure management',
      description: 'The organisation manages its network and information systems securely, with appropriate change control and monitoring in place.',
      description_nl: 'The organisation manages its network and information systems securely, with appropriate change control and monitoring in place.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B4 System Security',
      level: null,
      iso_mapping: 'A.12.1.2',
      implementation_guidance: 'Implement change management processes. Use secure administration practices including dedicated management networks where appropriate.',
      verification_guidance: 'Review change management records. Verify secure administration practices.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-4-system-security',
    },
    {
      control_number: 'B4.d',
      title: 'Vulnerability management',
      title_nl: 'Vulnerability management',
      description: 'The organisation identifies, triages, and remediates known vulnerabilities in its network and information systems within appropriate timeframes.',
      description_nl: 'The organisation identifies, triages, and remediates known vulnerabilities in its network and information systems within appropriate timeframes.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B4 System Security',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Conduct regular vulnerability scanning. Triage vulnerabilities based on risk. Apply patches within defined timeframes. Track remediation progress.',
      verification_guidance: 'Review vulnerability scan results and remediation timelines. Verify patching is within target timeframes.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-4-system-security',
    },
    // B5 Resilient Networks and Systems
    {
      control_number: 'B5.a',
      title: 'Resilience preparation',
      title_nl: 'Resilience preparation',
      description: 'The organisation has designed and built resilience into its network and information systems to maintain continuity of essential functions during disruptions or cyber attack.',
      description_nl: 'The organisation has designed and built resilience into its network and information systems to maintain continuity of essential functions during disruptions or cyber attack.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B5 Resilient Networks and Systems',
      level: null,
      iso_mapping: 'A.17.1.1',
      implementation_guidance: 'Design systems with redundancy for critical components. Implement backup and recovery procedures. Test resilience through tabletop exercises and simulations.',
      verification_guidance: 'Review system architecture for single points of failure. Verify backup and recovery testing is conducted regularly.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-5-resilient-networks-and-systems',
    },
    {
      control_number: 'B5.b',
      title: 'Design for resilience',
      title_nl: 'Design for resilience',
      description: 'Network and information systems are designed to be resilient. The design takes into account the need to maintain essential functions during adverse conditions, including cyber attack.',
      description_nl: 'Network and information systems are designed to be resilient. The design takes into account the need to maintain essential functions during adverse conditions, including cyber attack.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B5 Resilient Networks and Systems',
      level: null,
      iso_mapping: 'A.17.1.2',
      implementation_guidance: 'Apply defence in depth principles. Design for graceful degradation under attack. Implement network segmentation to contain breaches.',
      verification_guidance: 'Review architecture for defence in depth. Verify network segmentation is effective.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-5-resilient-networks-and-systems',
    },
    {
      control_number: 'B5.c',
      title: 'Backups',
      title_nl: 'Backups',
      description: 'The organisation maintains appropriately tested backups of data, configuration, and software needed to recover essential functions.',
      description_nl: 'The organisation maintains appropriately tested backups of data, configuration, and software needed to recover essential functions.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B5 Resilient Networks and Systems',
      level: null,
      iso_mapping: 'A.12.3.1',
      implementation_guidance: 'Implement automated backup procedures. Store backups securely (offline or immutable). Test restoration regularly. Maintain backup documentation.',
      verification_guidance: 'Verify backup schedule and retention. Test backup restoration. Review backup storage security.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-5-resilient-networks-and-systems',
    },
    // B6 Staff Awareness and Training
    {
      control_number: 'B6.a',
      title: 'Cyber security culture',
      title_nl: 'Cyber security culture',
      description: 'The organisation has a positive culture of security awareness. Staff at all levels understand their role in keeping the organisation secure and are motivated to do so.',
      description_nl: 'The organisation has a positive culture of security awareness. Staff at all levels understand their role in keeping the organisation secure and are motivated to do so.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B6 Staff Awareness and Training',
      level: null,
      iso_mapping: 'A.7.2.2',
      implementation_guidance: 'Deliver regular security awareness training. Include cyber security in induction programmes. Conduct phishing simulations. Recognise and reward good security behaviour.',
      verification_guidance: 'Review training completion records. Assess phishing simulation results. Survey staff security awareness.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-6-staff-awareness-and-training',
    },
    {
      control_number: 'B6.b',
      title: 'Cyber security training',
      title_nl: 'Cyber security training',
      description: 'Appropriate cyber security training is provided to personnel who have roles relevant to the security of the organisation, tailored to their specific responsibilities.',
      description_nl: 'Appropriate cyber security training is provided to personnel who have roles relevant to the security of the organisation, tailored to their specific responsibilities.',
      category: 'Protecting Against Cyber Attack',
      subcategory: 'B6 Staff Awareness and Training',
      level: null,
      iso_mapping: 'A.7.2.2',
      implementation_guidance: 'Identify security training needs based on roles. Provide role-specific training (e.g., secure development for developers, incident handling for security staff). Track training completion.',
      verification_guidance: 'Review training programme content. Verify role-based training is provided and tracked.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/b-6-staff-awareness-and-training',
    },
    // Objective C: Detecting Cyber Security Events
    // C1 Security Monitoring
    {
      control_number: 'C1.a',
      title: 'Monitoring coverage',
      title_nl: 'Monitoring coverage',
      description: 'The organisation has appropriate monitoring in place to detect cyber security events that may affect the security of network and information systems or the operation of essential functions.',
      description_nl: 'The organisation has appropriate monitoring in place to detect cyber security events that may affect the security of network and information systems or the operation of essential functions.',
      category: 'Detecting Cyber Security Events',
      subcategory: 'C1 Security Monitoring',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Deploy monitoring across all critical systems, networks, and data flows. Implement centralised log collection. Define monitoring use cases for known attack patterns.',
      verification_guidance: 'Review monitoring coverage against asset inventory. Verify log collection is functioning. Check monitoring use cases are defined.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/c-1-security-monitoring',
    },
    {
      control_number: 'C1.b',
      title: 'Securing logs',
      title_nl: 'Securing logs',
      description: 'Generated logs are stored securely and are available for analysis. Logs are protected from unauthorised access and tampering.',
      description_nl: 'Generated logs are stored securely and are available for analysis. Logs are protected from unauthorised access and tampering.',
      category: 'Detecting Cyber Security Events',
      subcategory: 'C1 Security Monitoring',
      level: null,
      iso_mapping: 'A.12.4.2',
      implementation_guidance: 'Store logs in a centralised, tamper-resistant system. Apply access controls to log data. Define log retention periods. Synchronise time sources.',
      verification_guidance: 'Verify log storage security and access controls. Check log retention compliance. Confirm time synchronisation.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/c-1-security-monitoring',
    },
    {
      control_number: 'C1.c',
      title: 'Generating alerts',
      title_nl: 'Generating alerts',
      description: 'The organisation defines detection rules and thresholds that generate alerts when potentially malicious activity is detected.',
      description_nl: 'The organisation defines detection rules and thresholds that generate alerts when potentially malicious activity is detected.',
      category: 'Detecting Cyber Security Events',
      subcategory: 'C1 Security Monitoring',
      level: null,
      iso_mapping: 'A.16.1.2',
      implementation_guidance: 'Define alerting rules for suspicious activities. Tune thresholds to balance detection sensitivity with false positive rates. Ensure alerts are routed to appropriate responders.',
      verification_guidance: 'Review alerting rules and thresholds. Verify alerts reach security operations. Check false positive rates.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/c-1-security-monitoring',
    },
    {
      control_number: 'C1.d',
      title: 'Identifying security incidents',
      title_nl: 'Identifying security incidents',
      description: 'The organisation has the capability to detect and investigate security events, and to identify security incidents from the data collected through monitoring.',
      description_nl: 'The organisation has the capability to detect and investigate security events, and to identify security incidents from the data collected through monitoring.',
      category: 'Detecting Cyber Security Events',
      subcategory: 'C1 Security Monitoring',
      level: null,
      iso_mapping: 'A.16.1.4',
      implementation_guidance: 'Establish security event analysis capability. Define criteria for escalating events to incidents. Maintain a security operations team or service.',
      verification_guidance: 'Review incident identification process. Verify analysis capability and staffing.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/c-1-security-monitoring',
    },
    // C2 Proactive Security Event Discovery
    {
      control_number: 'C2.a',
      title: 'System abnormalities for attack detection',
      title_nl: 'System abnormalities for attack detection',
      description: 'The organisation proactively discovers malicious activity or security weaknesses in its network and information systems. This includes threat hunting and proactive vulnerability discovery.',
      description_nl: 'The organisation proactively discovers malicious activity or security weaknesses in its network and information systems. This includes threat hunting and proactive vulnerability discovery.',
      category: 'Detecting Cyber Security Events',
      subcategory: 'C2 Proactive Security Event Discovery',
      level: null,
      iso_mapping: 'A.12.6.1',
      implementation_guidance: 'Conduct proactive threat hunting activities. Perform regular penetration testing. Use threat intelligence to guide detection efforts.',
      verification_guidance: 'Review threat hunting reports and penetration test results. Verify threat intelligence feeds are integrated.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/c-2-proactive-security-event-discovery',
    },
    // Objective D: Minimising the Impact of Cyber Security Incidents
    // D1 Response and Recovery Planning
    {
      control_number: 'D1.a',
      title: 'Response plan',
      title_nl: 'Response plan',
      description: 'The organisation has an incident response plan that is relevant, up to date, and tested. The plan addresses a range of incident scenarios including cyber attack.',
      description_nl: 'The organisation has an incident response plan that is relevant, up to date, and tested. The plan addresses a range of incident scenarios including cyber attack.',
      category: 'Minimising Impact',
      subcategory: 'D1 Response and Recovery Planning',
      level: null,
      iso_mapping: 'A.16.1.5',
      implementation_guidance: 'Develop and maintain an incident response plan. Include roles, responsibilities, communication plans, and escalation procedures. Test the plan regularly through exercises.',
      verification_guidance: 'Review incident response plan. Verify it covers cyber-specific scenarios. Check that exercises have been conducted.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/d-1-response-and-recovery-planning',
    },
    {
      control_number: 'D1.b',
      title: 'Response and recovery capability',
      title_nl: 'Response and recovery capability',
      description: 'The organisation maintains the capability to respond to and recover from the impact of a cyber security incident affecting its essential functions.',
      description_nl: 'The organisation maintains the capability to respond to and recover from the impact of a cyber security incident affecting its essential functions.',
      category: 'Minimising Impact',
      subcategory: 'D1 Response and Recovery Planning',
      level: null,
      iso_mapping: 'A.17.1.1',
      implementation_guidance: 'Maintain an incident response team with defined roles. Ensure recovery capabilities are tested. Document recovery time objectives and recovery point objectives.',
      verification_guidance: 'Verify incident response team readiness. Review recovery test results. Check RTO and RPO documentation.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/d-1-response-and-recovery-planning',
    },
    {
      control_number: 'D1.c',
      title: 'Testing and exercising',
      title_nl: 'Testing and exercising',
      description: 'The organisation regularly tests its response and recovery capabilities to ensure they are effective, and exercises are used to validate and improve plans.',
      description_nl: 'The organisation regularly tests its response and recovery capabilities to ensure they are effective, and exercises are used to validate and improve plans.',
      category: 'Minimising Impact',
      subcategory: 'D1 Response and Recovery Planning',
      level: null,
      iso_mapping: 'A.17.1.3',
      implementation_guidance: 'Conduct regular incident response exercises including tabletop and live simulations. Test backup restoration procedures. Document findings and update plans.',
      verification_guidance: 'Review exercise schedules and reports. Verify lessons learned are incorporated into plans.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/d-1-response-and-recovery-planning',
    },
    // D2 Lessons Learned
    {
      control_number: 'D2.a',
      title: 'Incident root cause analysis',
      title_nl: 'Incident root cause analysis',
      description: 'When a cyber security incident occurs, the organisation conducts a root cause analysis and takes steps to learn from the incident and improve its security posture.',
      description_nl: 'When a cyber security incident occurs, the organisation conducts a root cause analysis and takes steps to learn from the incident and improve its security posture.',
      category: 'Minimising Impact',
      subcategory: 'D2 Lessons Learned',
      level: null,
      iso_mapping: 'A.16.1.6',
      implementation_guidance: 'Conduct post-incident reviews for all significant incidents. Identify root causes and contributing factors. Implement improvements based on findings.',
      verification_guidance: 'Review post-incident reports. Verify that recommended improvements are tracked and implemented.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/d-2-lessons-learned',
    },
    {
      control_number: 'D2.b',
      title: 'Using incidents to drive improvements',
      title_nl: 'Using incidents to drive improvements',
      description: 'Lessons learned from incidents and exercises are used to drive improvements to the security of network and information systems.',
      description_nl: 'Lessons learned from incidents and exercises are used to drive improvements to the security of network and information systems.',
      category: 'Minimising Impact',
      subcategory: 'D2 Lessons Learned',
      level: null,
      iso_mapping: 'A.16.1.6',
      implementation_guidance: 'Maintain a lessons learned register. Track improvement actions arising from incidents and exercises. Report progress to senior management.',
      verification_guidance: 'Review lessons learned register. Verify improvement actions are progressing.',
      source_url: 'https://www.ncsc.gov.uk/collection/caf/caf-principles-and-guidance/d-2-lessons-learned',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-caf.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
