// scripts/ingest-ncsc-cloud.ts
// NCSC Cloud Security Principles — 14 principles for secure cloud usage
// Source: https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '..', 'data', 'extracted');
mkdirSync(OUTPUT_DIR, { recursive: true });

const data = {
  framework: {
    id: 'ncsc-cloud',
    name: 'NCSC Cloud Security Principles',
    name_nl: 'NCSC Cloud Security Principles',
    issuing_body: 'National Cyber Security Centre (NCSC-UK)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: '14 principles to help organisations evaluate the security of cloud services and make informed procurement decisions',
    scope_sectors: ['government', 'all'],
    structure_description: '14 numbered principles covering data protection, service operation, personnel, and supply chain in cloud environments',
    source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles',
    license: 'Open Government Licence v3.0',
    language: 'en',
  },
  controls: [
    {
      control_number: '1',
      title: 'Data in transit protection',
      title_nl: 'Data in transit protection',
      description: 'User data transiting networks should be adequately protected against tampering and eavesdropping. Protection should be achieved through a combination of network protection and encryption.',
      description_nl: 'User data transiting networks should be adequately protected against tampering and eavesdropping. Protection should be achieved through a combination of network protection and encryption.',
      category: 'Data Protection',
      subcategory: 'Transit',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Ensure all data transmitted between the user and the cloud service, and between cloud service components, is encrypted using TLS 1.2 or later. Verify certificate validity and pinning where appropriate.',
      verification_guidance: 'Test TLS configurations on all endpoints. Verify no data is transmitted in cleartext.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-1-data-in-transit-protection',
    },
    {
      control_number: '2',
      title: 'Asset protection and resilience',
      title_nl: 'Asset protection and resilience',
      description: 'User data, and the assets storing or processing it, should be protected against physical tampering, loss, damage, and seizure. Physical security, data sanitisation, equipment disposal, and resilience and availability measures all apply.',
      description_nl: 'User data, and the assets storing or processing it, should be protected against physical tampering, loss, damage, and seizure. Physical security, data sanitisation, equipment disposal, and resilience and availability measures all apply.',
      category: 'Data Protection',
      subcategory: 'Physical and resilience',
      level: null,
      iso_mapping: 'A.11.1.1',
      implementation_guidance: 'Understand where data is physically stored and processed. Verify the cloud provider has appropriate physical security controls, data sanitisation procedures, and resilience capabilities.',
      verification_guidance: 'Review cloud provider data centre certifications. Verify data residency requirements are met. Check resilience architecture.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-2-asset-protection-and-resilience',
    },
    {
      control_number: '3',
      title: 'Separation between consumers',
      title_nl: 'Separation between consumers',
      description: 'A malicious or compromised user of the service should not be able to affect the service or data of another user. Isolation controls should prevent unauthorised cross-tenant access.',
      description_nl: 'A malicious or compromised user of the service should not be able to affect the service or data of another user. Isolation controls should prevent unauthorised cross-tenant access.',
      category: 'Service Operation',
      subcategory: 'Tenant isolation',
      level: null,
      iso_mapping: 'A.13.1.3',
      implementation_guidance: 'Understand the isolation model used by the cloud provider (hypervisor, container, logical). Assess whether the isolation is appropriate for the sensitivity of the data.',
      verification_guidance: 'Review the cloud provider isolation architecture. Conduct penetration testing for cross-tenant access.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-3-separation-between-users',
    },
    {
      control_number: '4',
      title: 'Governance framework',
      title_nl: 'Governance framework',
      description: 'The service provider should have a security governance framework that coordinates and directs its management of the service and information within it. Any technical controls deployed outside of this framework will be undermined.',
      description_nl: 'The service provider should have a security governance framework that coordinates and directs its management of the service and information within it. Any technical controls deployed outside of this framework will be undermined.',
      category: 'Service Operation',
      subcategory: 'Governance',
      level: null,
      iso_mapping: '5.1',
      implementation_guidance: 'Verify the cloud provider has documented security policies, a defined governance structure, and regular compliance assessments (e.g., ISO 27001, SOC 2).',
      verification_guidance: 'Request and review cloud provider governance documentation and audit certificates.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-4-governance-framework',
    },
    {
      control_number: '5',
      title: 'Operational security',
      title_nl: 'Operational security',
      description: 'The service needs to be operated and managed securely to impede, detect, or prevent attacks. Good operational security should not require complex, bureaucratic, time-consuming, or expensive processes.',
      description_nl: 'The service needs to be operated and managed securely to impede, detect, or prevent attacks. Good operational security should not require complex, bureaucratic, time-consuming, or expensive processes.',
      category: 'Service Operation',
      subcategory: 'Operations',
      level: null,
      iso_mapping: 'A.12.1.1',
      implementation_guidance: 'Verify the cloud provider has documented operational procedures, change management processes, vulnerability management, and configuration management. Ensure operational security is proportionate.',
      verification_guidance: 'Review operational security procedures. Check change management and vulnerability management records.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-5-operational-security',
    },
    {
      control_number: '6',
      title: 'Personnel security',
      title_nl: 'Personnel security',
      description: 'Where service provider personnel have access to your data or systems, a high degree of confidence in their trustworthiness is required. Thorough screening, supported by adequate training, reduces the likelihood of accidental or malicious compromise.',
      description_nl: 'Where service provider personnel have access to your data or systems, a high degree of confidence in their trustworthiness is required. Thorough screening, supported by adequate training, reduces the likelihood of accidental or malicious compromise.',
      category: 'Personnel',
      subcategory: 'Staff screening',
      level: null,
      iso_mapping: 'A.7.1.1',
      implementation_guidance: 'Verify the cloud provider conducts pre-employment screening appropriate to the role. Ensure staff receive security awareness training. Check that access is removed promptly when staff leave.',
      verification_guidance: 'Request evidence of screening processes and training programmes. Review leavers access revocation process.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-6-personnel-security',
    },
    {
      control_number: '7',
      title: 'Secure development',
      title_nl: 'Secure development',
      description: 'Services should be designed and developed to identify and mitigate threats to their security. Those which are not may be vulnerable to security issues that could compromise data, cause loss of service, or enable other malicious activity.',
      description_nl: 'Services should be designed and developed to identify and mitigate threats to their security. Those which are not may be vulnerable to security issues that could compromise data, cause loss of service, or enable other malicious activity.',
      category: 'Service Operation',
      subcategory: 'Development',
      level: null,
      iso_mapping: 'A.14.2.1',
      implementation_guidance: 'Verify the cloud provider follows a secure development lifecycle. Check that code reviews, security testing, and threat modelling are part of the development process.',
      verification_guidance: 'Request evidence of secure development practices. Review penetration test and security assessment reports.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-7-secure-development',
    },
    {
      control_number: '8',
      title: 'Supply chain security',
      title_nl: 'Supply chain security',
      description: 'The service provider should ensure that its supply chain satisfactorily supports all of the security principles that the service claims to implement. Third-party components should not undermine the security of the overall service.',
      description_nl: 'The service provider should ensure that its supply chain satisfactorily supports all of the security principles that the service claims to implement. Third-party components should not undermine the security of the overall service.',
      category: 'Supply Chain',
      subcategory: 'Third-party management',
      level: null,
      iso_mapping: 'A.15.1.1',
      implementation_guidance: 'Understand the cloud provider sub-processors and supply chain. Verify that supply chain security requirements are proportionate and contractually enforced.',
      verification_guidance: 'Review the cloud provider sub-processor list. Check contractual security requirements for sub-processors.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-8-supply-chain-security',
    },
    {
      control_number: '9',
      title: 'Secure consumer management',
      title_nl: 'Secure consumer management',
      description: 'The service should make available the tools for consumers to securely manage their use of the service. Management interfaces and procedures are a key attack surface, and appropriate controls should be in place.',
      description_nl: 'The service should make available the tools for consumers to securely manage their use of the service. Management interfaces and procedures are a key attack surface, and appropriate controls should be in place.',
      category: 'Service Operation',
      subcategory: 'Consumer management',
      level: null,
      iso_mapping: 'A.9.4.1',
      implementation_guidance: 'Use the cloud provider management console securely. Enable MFA for administrative access. Restrict administrative access to authorised personnel. Monitor administrative actions.',
      verification_guidance: 'Verify MFA is enforced on management consoles. Review administrative access logs.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-9-secure-user-management',
    },
    {
      control_number: '10',
      title: 'Identity and authentication',
      title_nl: 'Identity and authentication',
      description: 'All access to service interfaces should be constrained to authenticated and authorised individuals. Weak authentication to these interfaces may enable unauthorised access, resulting in the theft or modification of data, changes to the service, or a denial of service.',
      description_nl: 'All access to service interfaces should be constrained to authenticated and authorised individuals. Weak authentication to these interfaces may enable unauthorised access, resulting in the theft or modification of data, changes to the service, or a denial of service.',
      category: 'Service Operation',
      subcategory: 'Authentication',
      level: null,
      iso_mapping: 'A.9.4.2',
      implementation_guidance: 'Use strong authentication mechanisms (MFA at minimum). Integrate with enterprise identity providers via federation (SAML, OIDC). Implement least privilege access control.',
      verification_guidance: 'Verify MFA is enforced for all access. Test authentication mechanisms. Review access control policies.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-10-identity-and-authentication',
    },
    {
      control_number: '11',
      title: 'External interface protection',
      title_nl: 'External interface protection',
      description: 'All external or less trusted interfaces of the service should be identified and appropriately defended. If some of the interfaces exposed are private (such as management interfaces), the impact of compromise may be more significant.',
      description_nl: 'All external or less trusted interfaces of the service should be identified and appropriately defended. If some of the interfaces exposed are private (such as management interfaces), the impact of compromise may be more significant.',
      category: 'Service Operation',
      subcategory: 'Interface protection',
      level: null,
      iso_mapping: 'A.13.1.1',
      implementation_guidance: 'Identify all external interfaces. Apply appropriate protections including firewalls, API gateways, and rate limiting. Restrict management interface access by IP or VPN.',
      verification_guidance: 'Inventory external interfaces. Test protections with vulnerability scanning and penetration testing.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-11-external-interface-protection',
    },
    {
      control_number: '12',
      title: 'Secure service administration',
      title_nl: 'Secure service administration',
      description: 'Systems used for administration of a cloud service will have highly privileged access to that service. Their compromise would have significant impact, including the means to bypass security controls and steal or manipulate large volumes of data.',
      description_nl: 'Systems used for administration of a cloud service will have highly privileged access to that service. Their compromise would have significant impact, including the means to bypass security controls and steal or manipulate large volumes of data.',
      category: 'Service Operation',
      subcategory: 'Administration',
      level: null,
      iso_mapping: 'A.9.4.4',
      implementation_guidance: 'Use dedicated, hardened devices for service administration. Apply MFA for administrative access. Restrict administrative connections to trusted networks. Log all administrative actions.',
      verification_guidance: 'Verify administrative device hardening. Check MFA enforcement for admin access. Review admin action logs.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-12-secure-service-administration',
    },
    {
      control_number: '13',
      title: 'Audit information and alerting',
      title_nl: 'Audit information and alerting',
      description: 'Consumers should be provided with the audit records and alerting they need to detect and respond to inappropriate or malicious use of their service or data within it.',
      description_nl: 'Consumers should be provided with the audit records and alerting they need to detect and respond to inappropriate or malicious use of their service or data within it.',
      category: 'Service Operation',
      subcategory: 'Audit and alerting',
      level: null,
      iso_mapping: 'A.12.4.1',
      implementation_guidance: 'Enable audit logging for all significant events. Configure alerting for suspicious activities. Export logs to your own SIEM for analysis. Define retention periods.',
      verification_guidance: 'Verify audit logging is enabled and complete. Test alerting rules. Check log export and retention.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-13-audit-information-for-users',
    },
    {
      control_number: '14',
      title: 'Secure use of the service',
      title_nl: 'Secure use of the service',
      description: 'The security of cloud services and the data held within them can be undermined if consumers use the service poorly. Consumers have certain responsibilities when using a cloud service for their data to be adequately protected.',
      description_nl: 'The security of cloud services and the data held within them can be undermined if consumers use the service poorly. Consumers have certain responsibilities when using a cloud service for their data to be adequately protected.',
      category: 'Consumer Responsibility',
      subcategory: 'Secure usage',
      level: null,
      iso_mapping: 'A.9.3.1',
      implementation_guidance: 'Configure the cloud service securely following provider guidance and NCSC recommendations. Implement the shared responsibility model. Regularly review security configuration.',
      verification_guidance: 'Audit cloud service configuration against security baselines. Verify shared responsibility model is understood and implemented.',
      source_url: 'https://www.ncsc.gov.uk/collection/cloud/the-cloud-security-principles/principle-14-secure-use-of-the-service',
    },
  ],
};

writeFileSync(join(OUTPUT_DIR, 'ncsc-cloud.json'), JSON.stringify(data, null, 2));
console.log(`Wrote ${data.controls.length} controls for ${data.framework.id}`);
